[workspace]
resolver = "2"

members = ["pika-proxy", "redis"]

[workspace.dependencies]
tokio = { version = "1.28", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "net",
    "io-util"
] }
anyhow = "1.0.71"
thiserror = "1.0"
tracing = "0.1.37"
